#!/usr/bin/env bash
# Audits a domain name and displays information about its subdomains

# shellcheck disable=SC2086

display_subdomain() {
    local subdomain=$1
    local dom=$2
    
    # Passing the variable as 'sub_name' to avoid the reserved 'sub' keyword in awk
    dig "$subdomain.$dom" A +noall +answer | awk -v sub_name="$subdomain" '{print "The subdomain " sub_name " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]; then
    display_subdomain "www" "$1"
    display_subdomain "lb-01" "$1"
    display_subdomain "web-01" "$1"
    display_subdomain "web-02" "$1"
elif [ "$#" -eq 2 ]; then
    display_subdomain "$2" "$1"
else
    exit 1
fi
