#!/usr/bin/env bash
# Audits a domain name and displays information about its subdomains

# shellcheck disable=SC2086

display_subdomain() {
    local subdomain=$1
    local dom=$2
    
    # The $4 == "A" condition forces awk to ignore dig headers and only parse the actual A record
    dig "$subdomain.$dom" A | awk -v sub_name="$subdomain" '$4 == "A" {print "The subdomain " sub_name " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]; then
    display_subdomain "www" "$1"
    display_subdomain "lb-01" "$1"
    display_subdomain "web-01" "$1"
    display_subdomain "web-02" "$1"
elif [ "$#" -eq 2 ]; then
    display_subdomain "$2" "$1"
else
    exit 1
fi
